apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zcp-alertmanager-store
  name: zcp-alertmanager-store
  namespace: zcp-system
spec:
  selector:
    matchLabels:
      app: zcp-alertmanager-store
  template:
    metadata:
      labels:
        app: zcp-alertmanager-store
    spec:
      tolerations:
      - key: "management"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
              - key: role
                operator: In
                values:
                - "management"
      containers:
      - image: registry.au-syd.bluemix.net/cloudzcp/zcp-alertmanager-store:1.0.0
        name: zcp-alertmanager-store
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
