apiVersion: v1
kind: Service
metadata:
  name: webhook-alertmanager-store-svc
  namespace: zcp-system 
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webhook-alertmanager-store
  type: ClusterIP 

