apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alertmanager-store
  name: alertmanager-store 
  namespace: zcp-system
spec:
  selector:
    matchLabels:
      app: alertmanager-store 
  template:
    metadata:
      labels:
        app: alertmanager-store 
    spec:
      containers:
      - image: cocopop1106/zcp-alertmanager-store:0.1
        name: alertmanager-store 
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
